import { Vehicle, Service } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: "1",
    brand: "Toyota",
    model: "AYGO",
    year: 2020,
    mileage: 32000,
    fuel: "Essence",
    price: 9900,
    transmission: "Automatique",
    power: 68,
    color: "Blanc",
    doors: 5,
    featured: true,
    description:
      "Toyota AYGO boîte automatique, Crit'Air 2. Idéale en ville, très économique. Vérifiée en 160 points, 250 km parcourus avant mise en vente. Garantie 6 à 12 mois kilométrages illimités. Révision boîte automatique effectuée.",
    images: [
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    ],
  },
  {
    id: "2",
    brand: "Nissan",
    model: "Micra",
    year: 2019,
    mileage: 48000,
    fuel: "Essence",
    price: 10500,
    transmission: "Automatique",
    power: 88,
    color: "Gris Métallisé",
    doors: 5,
    featured: true,
    description:
      "Nissan Micra 1.4 88 ch Acenta, boîte automatique, Crit'Air 2. Véhicule français, bien entretenu, carnet à jour. Vérification en 160 points. Garantie 6 à 12 mois km illimités. Révision boîte automatique incluse.",
    images: [
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80",
      "https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?w=800&q=80",
    ],
  },
  {
    id: "3",
    brand: "Suzuki",
    model: "Swift",
    year: 2018,
    mileage: 52000,
    fuel: "Essence",
    price: 11200,
    transmission: "Automatique",
    power: 94,
    color: "Rouge",
    doors: 5,
    featured: true,
    description:
      "Suzuki Swift 1.2i 94 ch GLX Pack, boîte automatique et toit ouvrant. Très bien équipée, climatisation, bluetooth. 250 à 500 km parcourus avant vente. Garantie 6 à 12 mois km illimités, vérification 160 points.",
    images: [
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
    ],
  },
  {
    id: "4",
    brand: "Nissan",
    model: "Pixo",
    year: 2017,
    mileage: 65000,
    fuel: "Essence",
    price: 7900,
    transmission: "Automatique",
    power: 68,
    color: "Argent",
    doors: 5,
    featured: true,
    description:
      "Nissan Pixo 1.0i 68 ch Acenta, boîte automatique, 1ère main. Petite citadine très maniable, consommation faible. Entretien complet réalisé. Garantie 6 à 12 mois km illimités, vérification 160 points.",
    images: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800&q=80",
    ],
  },
  {
    id: "5",
    brand: "Opel",
    model: "Agila",
    year: 2016,
    mileage: 72000,
    fuel: "Essence",
    price: 7200,
    transmission: "Automatique",
    power: 85,
    color: "Bleu",
    doors: 5,
    featured: false,
    description:
      "Opel Agila 1.2i 85 ch Edition, boîte automatique, 1ère main. Véhicule bien entretenu, révisé par notre atelier. Parfaite pour les déplacements quotidiens. Garantie 6 à 12 mois km illimités.",
    images: [
      "https://images.unsplash.com/photo-1617469767807-42f8d20f0be8?w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    ],
  },
  {
    id: "6",
    brand: "Hyundai",
    model: "i10",
    year: 2018,
    mileage: 58000,
    fuel: "Essence",
    price: 8900,
    transmission: "Automatique",
    power: 67,
    color: "Blanc",
    doors: 5,
    featured: false,
    description:
      "Hyundai i10 boîte automatique. Légère, économique et facile à garer. Parfaite pour la ville et les trajets courts. Véhicule contrôlé et révisé, prêt à rouler. Garantie 6 à 12 mois km illimités.",
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
      "https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=800&q=80",
    ],
  },
];

export const services: Service[] = [
  {
    id: "entretien",
    title: "Entretien & Révision",
    description:
      "Nous réalisons la mise au point moteur, la réparation de toute marque de véhicule ainsi que l'entretien général. Nous assurons la révision garantie constructeur, la vidange et la préparation pour le contrôle technique. Les préconisations constructeur sont toujours respectées.",
    icon: "wrench",
    features: [
      "Vidange huile moteur",
      "Remplacement filtres (air, habitacle, carburant)",
      "Révision garantie constructeur",
      "Remplacement courroie de distribution",
      "Préparation contrôle technique",
      "Remplacement disques et plaquettes de freins",
      "Révision et recharge de climatisation",
      "Remplacement batterie",
    ],
  },
  {
    id: "mecanique",
    title: "Réparation Mécanique",
    description:
      "Spécialistes BMW, Audi et Volkswagen, nos mécaniciens qualifiés et continuellement formés aux nouvelles technologies interviennent sur tous types de véhicules. Diagnostic électronique en 10 minutes. Un devis pièce et main-d'œuvre est établi avant toute intervention mécanique.",
    icon: "settings",
    features: [
      "Diagnostic OBD en 10 minutes",
      "Réparation moteur — spécialiste BMW · Audi · VW · Mercedes",
      "Remplacement embrayage et boîte de vitesses",
      "Réparation suspension, direction et amortisseurs",
      "Nettoyage et régénération filtre à particules",
      "Réparation turbo et vanne EGR",
      "Réparation boîte de vitesse automatique",
      "Mise au point moteur",
    ],
  },
  {
    id: "carrosserie",
    title: "Carrosserie & Peinture",
    description:
      "Notre atelier carrosserie est équipé d'une cabine de peinture neuve. Réparation d'ailes, débosselage, peinture teinte constructeur. Prise en charge du dossier d'assurance et d'expertise suite à un sinistre. Nettoyage intérieur et extérieur inclus après toute réparation de carrosserie.",
    icon: "paintbrush",
    features: [
      "Cabine de peinture neuve",
      "Débosselage et redressage carrosserie",
      "Peinture teinte constructeur",
      "Réparation et remplacement d'ailes",
      "Remplacement et réparation vitrage / pare-brise",
      "Prise en charge dossier assurance & expertise sinistre",
      "Nettoyage intérieur et extérieur inclus",
      "Rénovation optiques et phares",
    ],
  },
  {
    id: "diagnostic",
    title: "Diagnostic & Pannes",
    description:
      "Diagnostic électronique en 10 minutes pour tous constructeurs. Lecture et effacement des codes défaut OBD. Spécialistes de la combustion, tribologie et encrassements moteurs. Nettoyage et régénération DPF, gestion des pertes de puissance, réparation turbo et vanne EGR. Toutes marques.",
    icon: "cpu",
    features: [
      "Diagnostic en 10 minutes, toutes marques",
      "Lecture et effacement codes défaut OBD",
      "Nettoyage régénération filtre à particules",
      "Réparation turbo et vanne EGR",
      "Gestion pertes de puissance moteur",
      "Réparation boîte de transfert / servomoteur",
      "Test batterie et alternateur",
      "Reprogrammation calculateurs",
    ],
  },
];
