import { Vehicle, Service } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: "1",
    brand: "Toyota",
    model: "AYGO",
    year: 2020,
    mileage: 32000,
    fuel: "Essence",
    price: 9900,
    transmission: "Automatique",
    power: 68,
    color: "Blanc",
    doors: 5,
    featured: true,
    critAir: "2",
    isAvailable: true,
    description:
      "Toyota AYGO boîte automatique, Crit'Air 2. Idéale en ville, très économique. Vérifiée en 160 points, 250 km parcourus avant mise en vente. Garantie 6 à 12 mois kilométrages illimités. Révision boîte automatique effectuée.",
    features: {
      "Finition": "X-Play",
      "Motorisation": "1.0 VVT-i 68 ch",
      "Provenance": "Française",
      "Carnet d'entretien": "À jour",
      "Contrôle technique": "À jour",
      "Garantie": "6 à 12 mois km illimités",
      "Nb propriétaires": "1",
    },
    images: [
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    ],
  },
  {
    id: "2",
    brand: "Nissan",
    model: "Micra",
    year: 2019,
    mileage: 48000,
    fuel: "Essence",
    price: 10500,
    transmission: "Automatique",
    power: 88,
    color: "Gris Métallisé",
    doors: 5,
    featured: true,
    critAir: "2",
    isAvailable: true,
    description:
      "Nissan Micra 1.4 88 ch Acenta, boîte automatique, Crit'Air 2. Véhicule français, bien entretenu, carnet à jour. Vérification en 160 points, 250 km parcourus avant mise en vente. Garantie 6 à 12 mois km illimités. Révision boîte automatique incluse.",
    features: {
      "Finition": "Acenta",
      "Motorisation": "1.4 88 ch",
      "Provenance": "Française",
      "Carnet d'entretien": "À jour",
      "Contrôle technique": "À jour",
      "Garantie": "6 à 12 mois km illimités",
      "Nb propriétaires": "1",
    },
    images: [
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80",
      "https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?w=800&q=80",
    ],
  },
  {
    id: "3",
    brand: "Suzuki",
    model: "Swift",
    year: 2018,
    mileage: 52000,
    fuel: "Essence",
    price: 11200,
    transmission: "Automatique",
    power: 94,
    color: "Rouge",
    doors: 5,
    featured: true,
    critAir: "2",
    isAvailable: true,
    description:
      "Suzuki Swift 1.2i 94 ch GLX Pack, boîte automatique et toit ouvrant panoramique. Très bien équipée : climatisation automatique, bluetooth, régulateur de vitesse. 250 à 500 km parcourus avant mise en vente. Garantie 6 à 12 mois km illimités, vérification 160 points.",
    features: {
      "Finition": "GLX Pack",
      "Motorisation": "1.2i 94 ch",
      "Options": "Toit ouvrant, clim auto, bluetooth",
      "Provenance": "Française",
      "Carnet d'entretien": "À jour",
      "Contrôle technique": "À jour",
      "Garantie": "6 à 12 mois km illimités",
    },
    images: [
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
    ],
  },
  {
    id: "4",
    brand: "Nissan",
    model: "Pixo",
    year: 2017,
    mileage: 65000,
    fuel: "Essence",
    price: 7900,
    transmission: "Automatique",
    power: 68,
    color: "Argent",
    doors: 5,
    featured: true,
    critAir: "2",
    isAvailable: true,
    description:
      "Nissan Pixo 1.0i 68 ch Acenta, boîte automatique, 1ère main. Petite citadine très maniable, faible consommation. Entretien complet réalisé par notre atelier. Garantie 6 à 12 mois km illimités, vérification 160 points.",
    features: {
      "Finition": "Acenta",
      "Motorisation": "1.0i 68 ch",
      "Provenance": "Française",
      "Nb propriétaires": "1",
      "Carnet d'entretien": "À jour",
      "Contrôle technique": "À jour",
      "Garantie": "6 à 12 mois km illimités",
    },
    images: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800&q=80",
    ],
  },
  {
    id: "5",
    brand: "Opel",
    model: "Agila",
    year: 2016,
    mileage: 72000,
    fuel: "Essence",
    price: 7200,
    transmission: "Automatique",
    power: 85,
    color: "Bleu",
    doors: 5,
    featured: false,
    critAir: "2",
    isAvailable: true,
    description:
      "Opel Agila 1.2i 85 ch Edition, boîte automatique, 1ère main. Véhicule bien entretenu, révisé par notre atelier avant mise en vente. Parfaite pour les déplacements quotidiens. Garantie 6 à 12 mois km illimités.",
    features: {
      "Finition": "Edition",
      "Motorisation": "1.2i 85 ch",
      "Provenance": "Française",
      "Nb propriétaires": "1",
      "Carnet d'entretien": "À jour",
      "Contrôle technique": "À jour",
      "Garantie": "6 à 12 mois km illimités",
    },
    images: [
      "https://images.unsplash.com/photo-1617469767807-42f8d20f0be8?w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    ],
  },
  {
    id: "6",
    brand: "Hyundai",
    model: "i10",
    year: 2018,
    mileage: 58000,
    fuel: "Essence",
    price: 8900,
    transmission: "Automatique",
    power: 67,
    color: "Blanc",
    doors: 5,
    featured: false,
    critAir: "2",
    isAvailable: true,
    description:
      "Hyundai i10 boîte automatique. Légère, économique et facile à garer. Parfaite pour la ville et les trajets courts. Véhicule contrôlé et révisé par notre atelier, prêt à rouler. Garantie 6 à 12 mois km illimités.",
    features: {
      "Motorisation": "1.0i 67 ch",
      "Provenance": "Française",
      "Carnet d'entretien": "À jour",
      "Contrôle technique": "À jour",
      "Garantie": "6 à 12 mois km illimités",
    },
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
      "https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=800&q=80",
    ],
  },
];

export const services: Service[] = [
  {
    id: "entretien",
    title: "Entretien & Révision",
    description:
      "Motoriste spécialiste depuis plus de 12 ans, le Garage Mendonça assure l'entretien de tous les véhicules toutes marques avec un service de proximité, une écoute et une qualité d'intervention constante. Techniciens formés aux technologies Renault, PSA (Peugeot, Citroën), BMW, Audi et Volkswagen. Les préconisations constructeur sont toujours respectées.",
    icon: "wrench",
    features: [
      "Vidange huile moteur & remplacement filtres",
      "Révision garantie constructeur",
      "Remplacement courroie de distribution",
      "Préparation contrôle technique",
      "Pneus toutes marques — équipement Facom",
      "Climatisation — recharge, filtre pollen, traitement antibactérien",
      "Changement d'amortisseurs toutes marques",
      "Remplacement disques, plaquettes de freins & batterie",
    ],
  },
  {
    id: "mecanique",
    title: "Réparation Mécanique & Électronique",
    description:
      "À la fois généraliste et expert, le Garage Mendonça intervient aussi bien sur l'entretien courant que les réparations les plus techniques, sur tous les véhicules quelle que soit leur marque. Spécialistes BMW, Audi et Volkswagen, nos mécaniciens qualifiés et continuellement formés assurent le meilleur service. Réparation de pièces électroniques automobiles souvent hors de prix — à coût acceptable, en restant dans le réseau professionnel.",
    icon: "settings",
    features: [
      "Réparation moteur, embrayage & boîte de vitesses",
      "Suspensions, direction et amortisseurs",
      "Réparation pièces électroniques automobiles",
      "Spécialiste BMW · Audi · VW · Mercedes · Renault · PSA",
      "Réparation boîte de vitesse automatique",
      "Mise au point moteur",
      "Devis pièce & main-d'œuvre avant toute intervention",
      "Véhicule de prêt disponible",
    ],
  },
  {
    id: "diagnostic",
    title: "Diagnostic & Motoriste",
    description:
      "Votre Garage Mendonça, atelier conseil easydiag, est spécialiste de la combustion, de la tribologie et des encrassements moteurs depuis plus de 12 ans. Diagnostic électronique en 10 minutes sur tous constructeurs. Consultez-nous pour le nettoyage et la régénération de votre filtre à particules, toute perte de puissance moteur, un témoin OBD allumé, ou un turbo et une vanne EGR défaillants.",
    icon: "cpu",
    features: [
      "Diagnostic OBD / OBD2 en 10 minutes, toutes marques",
      "Nettoyage admission diesel",
      "Régénération & nettoyage DPF (filtre à particules)",
      "Réparation turbo & vanne EGR",
      "Gestion pertes de puissance moteur",
      "Lecture & effacement codes défaut",
      "Reprogrammation calculateurs",
      "Réparation boîte automatique & servomoteur",
    ],
  },
  {
    id: "carrosserie",
    title: "Carrosserie, Vitrage & Services",
    description:
      "Le Garage Mendonça a investi dans une toute nouvelle cabine de peinture pour des finitions irréprochables. Spécialisé dans les petits travaux de tôlerie et la simple collision, toutes marques (Renault, Peugeot, BMW, Mercedes, Volkswagen…). Remplacement de pare-brise et lunette arrière pour particuliers et utilitaires. Véhicule de courtoisie disponible, dossier assurance pris en charge intégralement.",
    icon: "paintbrush",
    features: [
      "Tôlerie, peinture, réparation plastiques — cabine neuve",
      "Pare-brise & lunette arrière (particuliers et utilitaires)",
      "Rénovation optiques et phares",
      "Prise en charge véhicule grêlé",
      "Dossier assurance & expertise sinistre",
      "Véhicule de courtoisie (gratuit ou 16 € HT/j)",
      "Location de véhicules (déménagements, déplacements pro)",
      "Nettoyage intérieur & extérieur inclus après carrosserie",
    ],
  },
];
